import type { Metadata } from 'next'
import { Inter, Montserrat, Nunito_Sans } from 'next/font/google'

import Footer from '@/components/footer/footer'
import Header from '@/components/header/header'

import '../styles/globals.scss'

const nunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  subsets: ['latin']
})

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin']
})

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'VintoGroup',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${nunitoSans.variable} ${montserrat.variable} ${inter.variable}`}
      >
    <Header />
    <div className='main'>{children}</div>
        <Footer />
      </body>
    </html>
  )
}
